import path from "path";
import fs from "fs";
import type { PhaseDefinition, PhaseResult, PipelineContext } from "../types";
import { exec } from "../exec";
import { generateEnvVars } from "../config";

const PHASE = "04-environment";

// Keys required for each mode
const REQUIRED_KEYS: Record<string, string[]> = {
  local: ["INFERENCE_MODE", "OLLAMA_URL", "POSTGRES_PASSWORD", "NEXTAUTH_SECRET", "LANGFUSE_SALT"],
  cloud: ["INFERENCE_MODE", "POSTGRES_PASSWORD", "NEXTAUTH_SECRET", "LANGFUSE_SALT"],
  hybrid: ["INFERENCE_MODE", "OLLAMA_URL", "POSTGRES_PASSWORD", "NEXTAUTH_SECRET", "LANGFUSE_SALT"],
};

const CLOUD_KEY_CANDIDATES = ["ANTHROPIC_API_KEY", "OPENAI_API_KEY"];

export const phase: PhaseDefinition = {
  id: "04-environment",
  name: "Environment",
  description: "Generate .env from template + customer.env and write to project root",
  dependencies: ["02-dependencies"],

  run: async (ctx: PipelineContext): Promise<PhaseResult> => {
    const startedAt = new Date().toISOString();
    const warnings: string[] = [];

    ctx.logger.info(PHASE, "Generating environment variables", {
      mode: ctx.mode,
      customer: ctx.customer.name,
    });

    // Locate the project root: the directory containing docker-compose.yml.
    // Walk up from customerDir until we find it, or fall back to customerDir.
    let projectRoot = ctx.customerDir;
    {
      let dir = ctx.customerDir;
      for (let i = 0; i < 6; i++) {
        const candidate = path.join(dir, "docker-compose.yml");
        try {
          fs.accessSync(candidate);
          projectRoot = dir;
          break;
        } catch {
          const parent = path.dirname(dir);
          if (parent === dir) break;
          dir = parent;
        }
      }
    }

    ctx.logger.debug(PHASE, "Project root resolved", { projectRoot });

    // Build the env vars map
    const envVars = generateEnvVars(
      ctx.hardware,
      ctx.mode,
      ctx.customerEnv,
      ctx.customer.name,
    );

    // Validate required keys
    const required = REQUIRED_KEYS[ctx.mode] ?? REQUIRED_KEYS.cloud;
    const keysSet: string[] = [];
    const keysMissing: string[] = [];

    for (const key of required) {
      if (envVars[key]) {
        keysSet.push(key);
      } else {
        keysMissing.push(key);
      }
    }

    // Cloud/hybrid: warn if no API keys present
    if (ctx.mode === "cloud" || ctx.mode === "hybrid") {
      const hasCloudKey = CLOUD_KEY_CANDIDATES.some((k) => envVars[k]);
      if (!hasCloudKey) {
        const msg = `No cloud API key found (checked: ${CLOUD_KEY_CANDIDATES.join(", ")})`;
        ctx.logger.warn(PHASE, msg);
        warnings.push(msg);
      } else {
        const presentKeys = CLOUD_KEY_CANDIDATES.filter((k) => envVars[k]);
        keysSet.push(...presentKeys);
        ctx.logger.info(PHASE, "Cloud API keys present", { keys: presentKeys });
      }
    }

    if (keysMissing.length > 0) {
      const msg = `Missing required env keys for mode "${ctx.mode}": ${keysMissing.join(", ")}`;
      ctx.logger.error(PHASE, msg);
      return {
        id: "04-environment",
        status: "failed",
        startedAt,
        completedAt: new Date().toISOString(),
        output: { envPath: null, mode: ctx.mode, keysSet, keysMissing },
        error: msg,
        warnings,
      };
    }

    // Render .env content
    const envLines = Object.entries(envVars)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([k, v]) => `${k}=${v}`);
    const envContent = [
      `# Generated by HEKLA setup pipeline — ${new Date().toISOString()}`,
      `# Mode: ${ctx.mode}`,
      `# Customer: ${ctx.customer.name}`,
      "",
      ...envLines,
      "",
    ].join("\n");

    const envPath = path.join(projectRoot, ".env");

    if (ctx.dryRun) {
      ctx.logger.info(PHASE, "[dry-run] Would write .env", { envPath });
      ctx.logger.debug(PHASE, "[dry-run] .env content", { content: envContent });
    } else {
      ctx.logger.info(PHASE, "Writing .env", { envPath });
      fs.writeFileSync(envPath, envContent, { encoding: "utf8", mode: 0o600 });
      ctx.logger.info(PHASE, ".env written", { envPath, keys: keysSet.length });
    }

    return {
      id: "04-environment",
      status: "completed",
      startedAt,
      completedAt: new Date().toISOString(),
      output: { envPath, mode: ctx.mode, keysSet, keysMissing },
      warnings,
    };
  },
};
